// SPDX-License-Identifier: GPL-3.0-or-later
#include "catalog.h"
namespace natural {
const Operation operations[]={
 {"Algebra","Simplify","simplify",1,{""},{"Expression"},false},
 {"Algebra","Expand brackets","expand",1,{""},{"Expression"},false},
 {"Algebra","Factorise","factor",1,{""},{"Expression"},false},
 {"Algebra","Partial fractions","partfrac",2,{"","x"},{"Fraction","Variable"},false},
 {"Algebra","Collect powers","collect",2,{"","x"},{"Expression","Variable"},false},
 {"Algebra","Substitute a value","subst",3,{"","x",""},{"Expression","Variable","Value"},false},
 {"Algebra","Polynomial remainder","rem",2,{"",""},{"Dividend","Divisor"},false},
 {"Algebra","Polynomial quotient","quo",2,{"",""},{"Dividend","Divisor"},false},
 {"Algebra","Coefficient of a power","coeff",3,{"","x","2"},{"Polynomial","Variable","Power"},false},
 {"Solve","Solve an equation","solve",2,{"","x"},{"Equation","Variable"},false},
 {"Solve","Numerical solution","fsolve",2,{"","x=1.0"},{"Equation","Variable = initial guess"},false},
 {"Solve","Complex solutions","csolve",2,{"","x"},{"Equation","Variable"},false},
 {"Solve","Simultaneous equations","linsolve",2,{"[x+y=3,x-y=1]","[x,y]"},{"Equations in a list","Variables in a list"},false},
 {"Solve","Polynomial roots (decimal)","proot",1,{""},{"Polynomial"},false},
 {"Calculus","Differentiate","diff",2,{"","x"},{"Expression","Variable"},true},
 {"Calculus","Nth derivative","diff",3,{"","x","2"},{"Expression","Variable","Order"},true},
 {"Calculus","Indefinite integral","integrate",2,{"","x"},{"Integrand","Variable"},true},
 {"Calculus","Definite integral","integrate",4,{"","x","0","1"},{"Integrand","Variable","Lower limit","Upper limit"},true},
 {"Calculus","Limit","limit",2,{"","x=0"},{"Expression","Variable = approach value"},true},
 {"Calculus","Taylor / Maclaurin series","taylor",3,{"","x=0","5"},{"Expression","Variable = centre","Order"},true},
 {"Calculus","Sum a sequence","sum",4,{"","k","1","n"},{"Term","Index","First index","Last index"},false},
 {"Calculus","Product of a sequence","product",4,{"","k","1","n"},{"Term","Index","First index","Last index"},false},
 {"Calculus","Differential equation","desolve",3,{"y'=2*y","x","y"},{"Equation or list with initial conditions","Independent variable","Dependent variable"},true},
 {"Calculus","Recurrence relation","rsolve",3,{"u(n+1)=2*u(n)+3","u(n)","u(0)=1"},{"Recurrence","Sequence","Initial condition"},false},
 {"Matrices","Determinant","det",1,{""},{"Matrix"},false},
 {"Matrices","Inverse","inv",1,{""},{"Matrix"},false},
 {"Matrices","Transpose","tran",1,{""},{"Matrix"},false},
 {"Matrices","Reduced row echelon form","rref",1,{""},{"Matrix"},false},
 {"Matrices","Rank","rank",1,{""},{"Matrix"},false},
 {"Matrices","Eigenvalues","eigenvals",1,{""},{"Matrix"},false},
 {"Matrices","Eigenvectors","eigenvects",1,{""},{"Matrix"},false},
 {"Matrices","Identity matrix","idn",1,{"3"},{"Order"},false},
 {"Matrices","Characteristic polynomial","charpoly",2,{"","x"},{"Matrix","Variable"},false},
 {"Matrices","LU decomposition","lu",1,{""},{"Matrix"},false},
 {"Vectors","Scalar / dot product","dot",2,{"[1,2,3]","[4,5,6]"},{"First vector","Second vector"},false},
 {"Vectors","Vector / cross product","cross",2,{"[1,2,3]","[4,5,6]"},{"First vector","Second vector"},false},
 {"Vectors","Magnitude","l2norm",1,{"[1,2,3]"},{"Vector"},false},
 {"Complex","Real part","re",1,{""},{"Complex number"},false},
 {"Complex","Imaginary part","im",1,{""},{"Complex number"},false},
 {"Complex","Modulus","abs",1,{""},{"Complex number"},false},
 {"Complex","Argument","arg",1,{""},{"Complex number"},false},
 {"Complex","Conjugate","conj",1,{""},{"Complex number"},false},
 {"Complex","Factor over complex numbers","cfactor",1,{""},{"Polynomial"},false},
 {"Probability","Binomial probability P(X=k)","binomial",3,{"10","1/2","3"},{"Trials n","Success probability p","Successes k"},false},
 {"Probability","Binomial cumulative P(X<=k)","binomial_cdf",3,{"10","1/2","3"},{"Trials n","Success probability p","Upper count k"},false},
 {"Probability","Normal cumulative P(X<=a)","normald_cdf",3,{"0","1","1.96"},{"Mean","Standard deviation","Upper value a"},false},
 {"Probability","Normal interval probability","normald_cdf",4,{"0","1","-1.96","1.96"},{"Mean","Standard deviation","Lower value","Upper value"},false},
 {"Probability","Inverse normal (quantile)","normald_icdf",3,{"0","1","0.975"},{"Mean","Standard deviation","Cumulative probability"},false},
 {"Probability","Poisson probability","poisson",2,{"3","2"},{"Mean lambda","Count k"},false},
 {"Probability","Poisson cumulative","poisson_cdf",2,{"3","2"},{"Mean lambda","Upper count k"},false},
 {"Probability","Combinations n choose r","comb",2,{"10","3"},{"n","r"},false},
 {"Statistics","Mean","mean",1,{"[2,4,6,8]"},{"Data list"},false},
 {"Statistics","Median","median",1,{"[2,4,6,8]"},{"Data list"},false},
 {"Statistics","Population standard deviation","stddev",1,{"[2,4,6,8]"},{"Data list"},false},
 {"Statistics","Sample standard deviation","stddevp",1,{"[2,4,6,8]"},{"Data list"},false},
 {"Statistics","Linear regression","linear_regression",2,{"[1,2,3,4]","[2,4,5,8]"},{"x data list","y data list"},false},
 {"Number","Greatest common divisor","gcd",2,{"",""},{"First integer / polynomial","Second integer / polynomial"},false},
 {"Number","Lowest common multiple","lcm",2,{"",""},{"First integer / polynomial","Second integer / polynomial"},false},
 {"Number","Prime factorisation","ifactor",1,{""},{"Integer"},false},
 {"Number","Primality test","isprime",1,{""},{"Integer"},false},
 {"Number","Integer remainder","irem",2,{"",""},{"Dividend","Divisor"},false},
 {"Graphs","Plot y = f(x)","plot",4,{"","x","-10","10"},{"Expression","Variable","x minimum","x maximum"},false},
 {"Graphs","Parametric curve","plotparam",2,{"[cos(t),sin(t)]","t=0..2*pi"},{"[x(t),y(t)]","Parameter interval"},true},
 {"Graphs","Polar curve","plotpolar",2,{"1+cos(t)","t=0..2*pi"},{"Radius function","Angle interval"},true},
 {"Graphs","Implicit curve","plotimplicit",3,{"x^2+y^2=4","x=-3..3","y=-3..3"},{"Equation","x interval","y interval"},false},
 {"Graphs","3D surface","plotfunc",2,{"x^2-y^2","[x=-3..3,y=-3..3]"},{"Expression","Domain"},false},
 {"Further maths","Stationary x coordinates","solve",2,{"diff(x^3-3*x,x)=0","x"},{"Derivative = 0","Variable"},true},
 {"Further maths","Roots of unity","csolve",2,{"z^4=1","z"},{"Equation","Variable"},false},
 {"Further maths","Hyperbolic sine","sinh",1,{""},{"Argument"},false},
 {"Further maths","Hyperbolic cosine","cosh",1,{""},{"Argument"},false},
 {"Further maths","Hyperbolic tangent","tanh",1,{""},{"Argument"},false}
};
const int operationCount=sizeof(operations)/sizeof(operations[0]);
}
